[package]
name = "csv_reader"
version = "0.1.0"
edition = "2021"

[lib]
# See https://github.com/PyO3/pyo3 for details
name = "_lib"  # private module to be nested into Python package
crate-type = ["cdylib"]
path = "rust/lib.rs"

[dependencies]
csv = "1.3.1"
pyo3 = { version = "0.23.2" }